### ISSUE TITLE
Emit file events for each included file

### ISSUE THREAD

**Issue by tjconcept** [srcagency/brjade#1]
In order for things like https://github.com/substack/watchify to properly work with jade-included files, this package should emit file events on each file in the bundle. I do not know if jade exposes these file names somehow.

**Comment by ForbesLindesay** [comment]
If you use `jade.compile` and `jade.compileFile` internally, rather than directly `jade.render`, you can get a list of dependencies.  e.g.

``` js
// instead of
var output = jade.render('foo bar', localsAndOptions);
// you can do
var fn = jade.compile('foo bar', localsAndOptions);
var dependencies = fn.dependencies;
var output = fn(localsAndOptions);
```

If you want to support inlining calls to `jade.compile` and `jade.compileFile` (i.e. inline them as a function, rather than inlining the final html) you would need to use the special `compileClientWithDependenciesTracked` api, that returns an object with `{body: 'a string of JavaScript to inline', dependencies: [..array of dependencies]}`

**Comment by tjconcept** [comment]
Thanks!

I guess there is no reason to pass options for the final rendering (`var output = fn()`), as these will always be identical to those passed to `.compile`?

**Comment by tjconcept** [comment]
> If you want to support inlining calls to `jade.compile` and `jade.compileFile`

I do not have a use case at the moment but it is a nice concept and I would welcome a PR if someone needs it.

**Comment by ForbesLindesay** [comment]
You need to pass the options to both.  They are treated entirely separately by jade.  The first is seen as options for jade (e.g. `compileDebug`) while the second is locals to be used in the template.

To emulate render, you must pass the same object to both.

**Comment by ForbesLindesay** [comment]
Would you like to move this repo to live in the @jadejs organisation?  That would give it lots more exposure, and allow more people to easily collaborate on development?  If you want to do that, could you add `forbeslindesay` as an owner on npm (i.e. run `npm owners add forbeslindesay`).

**Comment by tjconcept** [comment]
> To emulate render, you must pass the same object to both.

I'll fix this (later today) before publishing anything.

> Would you like to move this repo to live in the @jadejs organisation?

I would love to :-)
